name: docker
on:
  workflow_dispatch:
  release:
    types: [ "published" ]

jobs:
  docker:
    name: Docker image
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set application version
        run: sed -i "s#@box_git_version@#${{ github.ref_name }}#" bin/*.php
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ github.repository_owner }}/descarga-masiva"
          tags: "type=semver,pattern={{version}}"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
